### ISSUE TITLE
中間発表用スライド・質疑応答

### ISSUE THREAD

**Issue by kisayaha** [furuhashilab/2019gsc_TomokaHayasaki#2]
https://docs.google.com/presentation/d/1c5c4KFENGJNEPbjr8mK2Cpq4Rw29F4KXVTR06k2z4tE/edit?usp=sharing

**Comment by Keitaoba828** [comment]
安田の研究と上手く組み合わさったら、誰でもグラレコができるようになる気がしました！！

**Comment by harukayasuda** [comment]
使用目的に合わせて、使えるレイアウトがわかりすくなると一気に書くときのハードルは下がると思う

**Comment by LEEJIYUL** [comment]
専門的な講義に対して話を全然理解できない時に使えるマニュアルかアドバイスなどもあったらいいと思います

**Comment by MinoriIizuka** [comment]
参加者のためのグラレコは、自分のためよりハードルが高いように感じます。
人から見てわかりやすいグラレコが書けるようになるには…という視点のテンプレートがあると嬉しいです。

**Comment by Momotaroooo** [comment]
この前国際会議に参加してグラレコ書くのすごく難しかったので、型があるとやりやすそうだなって思いました！

**Comment by sy7676** [comment]
三パターンの中では複合型が最も全体を客観的に見れている資料だと感じた、前者二つを積極的に利用するメリットとは？

**Comment by reikomor** [comment]
ゼミだけでなく他の授業でも講義のグラレコが課題となっているので、グラレコの手法がわかるのは嬉しいです

**Comment by LEEJIYUL** [comment]
吹き出しの様な形でアドバイスをつけたらとっつきやすいかもしれません

**Comment by mapconcierge** [comment]
なるべく多くのプロのグラフィックレコーダー作品を見て、型をみつけていくのが効率よい！

**Comment by pppoon** [comment]
グラレコにも様々な種類があるんだなと思いました。

**Comment by naaao** [comment]
型はプレゼンで示された三種類を作るんですか？それともそれを主軸に細分化して作るんですか？

**Comment by shuntacarp** [comment]
ゼミ内サークル活動と、ゼミ論の活動を並行して行うということですか？

**Comment by ryuichianbo** [comment]
テンプレートがあると経験がなくてもできるようになると思うので早く使いたいです！

**Comment by 22hero1072** [comment]
現場困っていることとかありますか？？

**Comment by 22hero1072** [comment]
現場困っていることなどありますか？

**Comment by 23feat** [comment]
グラレコについて分かっていない人が多いと思うので役に立てたいです

**Comment by taizotaizo** [comment]
グラレコも多種多様だったのが興味深かったです！！

**Comment by harukayasuda** [comment]
ぐられことしての要素として、登壇者の背景が必須　グラレコの定義に関する議論したいね

**Comment by kokisano** [comment]
絵が上手くかけないひとが参加者のためにグラレコを作る際、絵以外ではどのような部分を書く必要があるか気になりました

**Comment by kisayaha** [comment]
> 三パターンの中では複合型が最も全体を客観的に見れている資料だと感じた、前者二つを積極的に利用するメリットとは？

講義形式ならレクチャー型、演説やTEDxならメッセージ型を使うのに向いていると、これまでの経験から感じています。講演の内容によって使い分けられるのが理想です。

**Comment by kisayaha** [comment]
> 型はプレゼンで示された三種類を作るんですか？それともそれを主軸に細分化して作るんですか？

これらはあくまで、これまでの経験から効果的だと感じた型です。プロのグラレコの分析や、さらなる実践を通して、新たな型を探していく予定です。この３パターンのみで進めていくかどうかは未定です。

**Comment by kisayaha** [comment]
> ゼミ内サークル活動と、ゼミ論の活動を並行して行うということですか？

その通りです。グラレコする機会があれば、積極的にゼミ論に繋げていこうと考えています。

**Comment by kisayaha** [comment]
> 現場困っていることなどありますか？

強いていうならば、外部の方からフィードバックをいただける機会が少ないこと？　これは積極的にイベントに参加することが解決策なのかなとも感じています。グラレコ部以外からも、FBやMediumにアップしたグラレコにコメントいただければうれしいです。
単純に難しいなと感じているのは、やはり専門用語が飛び交う講演やディスカッションのグラレコです。こういう場合は予習が欠かせないのですが、それ以外の解決策も探っていきます。
